### ISSUE TITLE
Make tray icon.

### ISSUE THREAD

**Issue by Ygarr** [vadrian89/cumulus-qt#2]
Make application tray
And ability to closing (minimizing) to tray.

**Comment by vadrian89** [comment]
It's on my do do list, even tough it isn't specifically mentioned on the front page, it's tied to "Hide Launcher option" from TODO. :)

**Comment by vadrian89** [comment]
Close to Tray has been implemented in the latest version, to update you have to solutions: 
1. Open Cumulus-maintenance application -> update.    
2. On start Cumulus will search for update after 1 min of uptime so on next start it will search and open Cumulus-maintenance itself    
It's recommended to close Cumulus before update.  
If it's ok, please let me know and close the issue using "Close and comment" option. If not please let me know the issue.

**Comment by vadrian89** [comment]
PS: I will add weather data to tray aswell, current + forecast, but need a bit of time :).

**Comment by vadrian89** [comment]
Going to close this since it was fixed.
