### ISSUE TITLE
Appimage build fail

### ISSUE THREAD

**Issue by vadrian89** [vadrian89/cumulus-qt#28]
I get this error: ERROR: Unknown argument "./appdir/usr/bin/qt.conf"   
I removed the qt.conf from project and removed the sed command, since it no longer points to a valid location but I don't know why this should affect the entire build.  
@probonopd , any info?

**Comment by probonopd** [comment]
Instead of `./appdir/usr/bin/*` use `./appdir/usr/share/applications/*desktop` in the two `linuxdeployqt` calls.
