### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [vadrian89/cumulus-qt#39]
Could you please clarify what license this project is using? According to what I see in some of the `.cpp` files, it seems to be GPL-3.0 (or later)? If you add the corresponding `LICENSE` file to the root of your repo, Github will detect it and mark your project accordingly.

Thanks in advance!

**Comment by vadrian89** [comment]
Hi, yes, it's GPL V3, didn't knew about that license file. Will add it to the project, thank you.

**Comment by vadrian89** [comment]
Added the license file. Again, thank you.

**Comment by IzzySoft** [comment]
Thanks to you! Now that's no longer causing confusion :smiley:
